name: dlproject_v4
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - audioread
  - pytorch
  - torchvision
  - pytorch-lightning
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - librosa
  - geopy
  - scikit-learn
  - scipy
  - pip
  - pip:
    - aifc
