name: SpectrogramClassifierEnv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - audioread
  - pytorch
  - torchvision
  - pytorch-lightning
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - librosa
  - geopy
  - scikit-learn
  - scipy
  - pip
  - pip:
    - aifc

# run these terminal command within the project directory to create the environment:
# module load miniconda3/20240410
# conda env create -f environment.yml 
# conda activate SpectrogramClassifierEnv

