name: SpectrogramClassifierEnv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - audioread
  - pytorch
  - torchvision
  - pytorch-lightning
  - numpy
  - pandas
  - jupyter
  - pickleshare
  - r-base
  - r-essentials
  - r-irkernel
  - nodejs
  - ipywidgets
  - matplotlib
  - seaborn
  - librosa
  - geopy
  - scikit-learn
  - scipy
  - pip
  - pip:
    - aifc
    - bash_kernel
    - git+https://github.com/conery/nbscan.git
    - tensorboardx


